### ISSUE TITLE
the test TestWICModels.test_wic_ger_ackergeraet_engpass fails

### ISSUE THREAD

**Issue by nvanva** [ChangeIsKey/LSCDBenchmark#53]
Running ```python -m unittest tests.integration.test_wic_models.TestWICModels.test_wic_ger_ackergeraet_engpass```
results in the AssertionError:
![image](https://github.com/user-attachments/assets/25f929f4-7deb-4623-97d1-f89129ea8153)

**Comment by Garrafao** [comment]
Should be solved with commit [f14714f](https://github.com/ChangeIsKey/LSCDBenchmark/commit/f14714fc678891199d7b61a1492ffaec3d170611). The [test word specification](https://github.com/ChangeIsKey/LSCDBenchmark/blob/f14714fc678891199d7b61a1492ffaec3d170611/tests/integration/test_wic_models.py#L33) was commented. Could you please retry?

**Comment by nvanva** [comment]
Still doesn't work, see the error attached. 
It seems that an English dataset is specified in the config
``` "dataset": "testwug_en_111"```, 
which probably doesn't contain German words
``` "dataset.test_on": ["Ackergerät", "Engpaß"],```
![image](https://github.com/user-attachments/assets/0b506eee-fd4a-40a1-a4db-4eac120ee555)

**Comment by Garrafao** [comment]
I think the test was never run before. I now exchanged it for this one:

    python -m unittest tests.integration.test_wic_models.TestWICModels.test_wic_eng_simple_plane_afternoon

I also tested running it, for me it works. Though the current assertion is trivial:

    assert score1 > 0.0

We should find more meaningful examples in the future.

**Comment by nvanva** [comment]
After fixing some imports it runs! I've commited the fixed imports.
